services:
  db_skill_hive:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: postgres_db_skill_hive
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reseau_interne_skill_hive

  api_skill_hive:
    # image: mahdimcheik/skill-hive-api:prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skill-hive-api
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      HOST_IP: ${HOST_IP}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      JWT_KEY: ${JWT_KEY}
      API_BACK_URL: ${API_BACK_URL}
      API_FRONT_URL: ${API_FRONT_URL}
      COOKIES_VALIDITY_DAYS: ${COOKIES_VALIDITY_DAYS}
      TOKEN_VALIDITY_MINUTES: ${TOKEN_VALIDITY_MINUTES}

      SMTP_BREVO_SERVER: ${SMTP_BREVO_SERVER}
      SMTP_BREVO_LOGIN: ${SMTP_BREVO_LOGIN}
      SMTP_BREVO_KEY: ${SMTP_BREVO_KEY}
      SMTP_BREVO_PORT: ${SMTP_BREVO_PORT}
      DO_NO_REPLY_MAIL: ${DO_NO_REPLY_MAIL}

      TEACHER_PASSWORD: ${TEACHER_PASSWORD}
      TEACHER_EMAIL: ${TEACHER_EMAIL}
      TEACHER_ID: ${TEACHER_ID}

      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_SECRET_ENDPOINT_TEST: ${STRIPE_SECRET_ENDPOINT_TEST}
      CHECKOUT_EXPIRY_DELAY: ${CHECKOUT_EXPIRY_DELAY}

      HANGFIRE_ORDER_CLEANING_DELAY: ${HANGFIRE_ORDER_CLEANING_DELAY}
    ports:
     - "${API_PORT}:${API_PORT}"
    # expose:
    #   - ${ASPNETCORE_HTTPS_PORT}
    networks:
      - reseau_interne_skill_hive
      # - just-add-network

    depends_on:
      db_skill_hive:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:

networks:
  reseau_interne_skill_hive:
    driver: bridge

  # just-add-network:
  #   external: true
