services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terminal_api
    environment:
      # ASP.NET Core Environment
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      
      # Override AppSettings with environment variables
      - AppSettings__Teacher__Guid=${TEACHER_GUID}
      - AppSettings__Teacher__Email=${TEACHER_EMAIL}
      
      - AppSettings__Api__FrontUrl=${API_FRONT_URL}
      - AppSettings__Api__BackUrl=${API_BACK_URL}
      
      - AppSettings__Database__Name=${DB_NAME}
      - AppSettings__Database__Port=${DB_PORT}
      - AppSettings__Database__User=${DB_USER}
      - AppSettings__Database__Password=${DB_PASSWORD}
      - AppSettings__Database__Host=${DB_HOST}
      - AppSettings__Database__ConnectionString=${DB_CONNECTION_STRING}
      - AppSettings__Database__Provider=${DB_PROVIDER}
      
      - AppSettings__Token__Audience=${TOKEN_AUDIENCE}
      - AppSettings__Token__Issuer=${TOKEN_ISSUER}
      - AppSettings__Token__JwtKey=${JWT_KEY}
      - AppSettings__Token__ValidityMinutes=${TOKEN_VALIDITY_MINUTES}
      
      - AppSettings__Smtp__BrevoKey=${SMTP_BREVO_KEY}
      - AppSettings__Smtp__BrevoServer=${SMTP_BREVO_SERVER}
      - AppSettings__Smtp__BrevoPort=${SMTP_BREVO_PORT}
      - AppSettings__Smtp__BrevoLogin=${SMTP_BREVO_LOGIN}
      
      - AppSettings__Mail__DoNotReplyMail=${DO_NO_REPLY_MAIL}
      
      - AppSettings__Google__ClientId=${GOOGLE_CLIENT_ID}
      - AppSettings__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - AppSettings__Google__RedirectUrl=${GOOGLE_REDIRECT_URL}
      - AppSettings__Google__ApiKey=${GOOGLE_API_KEY}
      
      - AppSettings__Stripe__SecretKey=${STRIPE_SECRET_KEY}
      - AppSettings__Stripe__PublishableKey=${STRIPE_PUBLISHABLE_KEY}
      - AppSettings__Stripe__SecretEndpointTest=${STRIPE_SECRET_ENDPOINT_TEST}
      
      - AppSettings__Hangfire__OrderCleaningDelayMinutes=${HANGFIRE_ORDER_CLEANING_DELAY_MINUTES}
      - AppSettings__Checkout__ExpiryDelayMinutes=${CHECKOUT_EXPIRY_DELAY_MINUTES}
      - AppSettings__Cookies__ValidityDays=${COOKIES_VALIDITY_DAYS}
      - AppSettings__Environment__DockerEnvironment=${DOCKER_ENVIRONMENT}
      
      # Override the main connection string as well
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

volumes:
  postgres_data:
