version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: beecoming
      POSTGRES_DB: terminaldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: TerminalApi/Dockerfile
    container_name: terminal_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=terminaldb;Username=postgres;Password=beecoming
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

volumes:
  postgres_data:
